DROP TABLE BIGDRIVERS cascade constraints;
DROP TABLE BIGCARS cascade constraints;
DROP TABLE CARS cascade constraints;
DROP TABLE DRIVERS cascade constraints;

CREATE TABLE DRIVERS (
    d_id NUMBER(5) PRIMARY KEY,
    first_name VARCHAR(30) NOT NULL,
    last_name VARCHAR(30) NOT NULL,
    address VARCHAR(60) NOT NULL,
    gender CHAR(1),
    phone_number NUMBER(11) UNIQUE,
    date_of_birth DATE,
    date_employed DATE,
    national_insurance VARCHAR(9) UNIQUE
);

CREATE TABLE CARS (
    registration VARCHAR(12) PRIMARY KEY,
    car_make VARCHAR(20),
    car_model VARCHAR(20),
    last_MOT DATE,
    status VARCHAR(20),
    d_id NUMBER(5),
    FOREIGN KEY (d_id) REFERENCES DRIVERS(d_id) ON DELETE SET NULL
);


CREATE TABLE BIGCARS (
    registration VARCHAR(12) ,
    car_make VARCHAR(20),
    car_model VARCHAR(20),
    last_MOT DATE,
    status VARCHAR(20),
    d_id NUMBER(5)
);

CREATE TABLE BIGDRIVERS (
    d_id NUMBER(5),
    first_name VARCHAR(30) NOT NULL,
    last_name VARCHAR(30) NOT NULL,
    address VARCHAR(60) NOT NULL,
    gender CHAR(1),
    phone_number NUMBER(11),
    date_of_birth DATE,
    date_employed DATE,
    national_insurance VARCHAR(9)
);


INSERT INTO DRIVERS VALUES(10000,'James','Smith','Linard Street AV 32', 'M', 07654765436, '01-JAN-98','11-JAN-18','PT034537A');
INSERT INTO DRIVERS VALUES(13300,'Stacey','Conor','Brum Street AV 12', 'F', 07683065436, '10-NOV-20','07-JUN-08','EH278153B');
INSERT INTO DRIVERS VALUES(12100,'Millard','Tempe','Ford Street AV 251', 'M', 07654524436, '20-MAR-79','11-AUG-98','OM044192C');
INSERT INTO DRIVERS VALUES(12120,'Mo','Crope','London Road ST 34', 'F', 07654760086, '11-JAN-95','08-NOV-19','TG702217B');
INSERT INTO DRIVERS VALUES(10100,'Appe','Niko','New cross AV 27', 'M', 07612365441, '03-APR-93','17-JAN-13','CS914945B');
INSERT INTO DRIVERS VALUES(10011,'Ronaldo','Vetty','Brum Road 233', 'M', 07654069457, '18-MAY-90','11-JAN-11','OE794542A');
INSERT INTO DRIVERS VALUES(13001,'Rhi','Biden','Manny Atown road', 'F', 07654711422, '04-JUL-92','01-DEC-14','NA112240C');

INSERT INTO CARS VALUES('DC4RTQ','HONDA','CIVIC','04 DEC 2019', 'Road Worthy', 13300);
INSERT INTO CARS VALUES('MA3RDT','MERCEDES','VITO','12 JAN 2020', 'Road Worthy', 12120);
INSERT INTO CARS VALUES('J9GF6D','TOYOTA','PRUIS','24 NOV 2019', 'Road Worthy', 12100);
INSERT INTO CARS VALUES('PHFJD7','FORD','FIESTA','04 DEC 2019', 'Road Worthy', 10000);
INSERT INTO CARS VALUES('H67DGF','HONDA','CIVIC','21 DEC 2019', 'Road Worthy', 13300);
INSERT INTO CARS VALUES('KD64HX','HONDA','CIVIC','12 AUG 2018', 'Road Worthy', 10100);
INSERT INTO CARS VALUES('Y40SK5','HONDA','CIVIC','04 DEC 2019', 'Written Off', NULL);
INSERT INTO CARS VALUES('HS63FD','TOYOTA','PRUIS','24 APR 2018', 'In for service', 10011);
INSERT INTO CARS VALUES('OSJ63F','FORD','FOCUS','24 NOV 2017', 'Road Worthy', 12100);
INSERT INTO CARS VALUES('SJR74H','TOYOTA','PRUIS','24 NOV 2017', 'Road Worthy', 12100);
INSERT INTO CARS VALUES('34JURI','TOYOTA','PRUIS','24 AUG 2020', 'Road Worthy', 13001);
INSERT INTO CARS VALUES('DHSHES','HONDA','CIVIC','04 DEC 2019', 'Written Off', NULL);
INSERT INTO CARS VALUES('SN64HB','HONDA','CIVIC','04 DEC 2019', 'Written Off', NULL);
INSERT INTO CARS VALUES('SMF74H','HONDA','CIVIC','04 DEC 2019', 'Written Off', NULL);
INSERT INTO CARS VALUES('MKFMJ6','HONDA','CIVIC','04 DEC 2019', 'Written Off', NULL);

INSERT INTO BIGCARS (SELECT * FROM CARS);
INSERT INTO BIGCARS (SELECT * FROM BIGCARS);
INSERT INTO BIGCARS (SELECT * FROM BIGCARS);
INSERT INTO BIGCARS (SELECT * FROM BIGCARS);
INSERT INTO BIGCARS (SELECT * FROM BIGCARS);
INSERT INTO BIGCARS (SELECT * FROM BIGCARS);
INSERT INTO BIGCARS (SELECT * FROM BIGCARS);


INSERT INTO BIGDRIVERS (SELECT * FROM DRIVERS);
INSERT INTO BIGDRIVERS (SELECT * FROM BIGDRIVERS);
INSERT INTO BIGDRIVERS (SELECT * FROM BIGDRIVERS);
INSERT INTO BIGDRIVERS (SELECT * FROM BIGDRIVERS);
INSERT INTO BIGDRIVERS (SELECT * FROM BIGDRIVERS);
INSERT INTO BIGDRIVERS (SELECT * FROM BIGDRIVERS);


-- Query 1
SELECT BIGCARS.registration, BIGCARS.car_make, BIGCARS.car_model, BIGDRIVERS.first_name, BIGDRIVERS.last_name FROM BIGCARS
FULL OUTER JOIN BIGDRIVERS
ON BIGCARS.d_id = BIGDRIVERS.d_id;
-- Query 2
SELECT A.registration, A.car_make, BIGDRIVERS.d_id FROM (SELECT * FROM BIGCARS WHERE BIGCARS.status !=  'Written Off') A
FULL OUTER JOIN BIGDRIVERS
ON A.d_id = BIGDRIVERS.d_id;


-- Adding more data
INSERT INTO BIGDRIVERS (SELECT * FROM BIGDRIVERS);
INSERT INTO BIGDRIVERS (SELECT * FROM BIGDRIVERS);
INSERT INTO BIGDRIVERS (SELECT * FROM BIGDRIVERS);
INSERT INTO BIGDRIVERS (SELECT * FROM BIGDRIVERS);
INSERT INTO BIGDRIVERS (SELECT * FROM BIGDRIVERS);


INSERT INTO BIGCARS (SELECT * FROM BIGCARS);
INSERT INTO BIGCARS (SELECT * FROM BIGCARS);
INSERT INTO BIGCARS (SELECT * FROM BIGCARS);
INSERT INTO BIGCARS (SELECT * FROM BIGCARS);
INSERT INTO BIGCARS (SELECT * FROM BIGCARS);


CREATE INDEX car_driver_id ON BIGCARS(d_id);

--QUERY 3
SELECT * FROM BIGCARS WHERE d_id=12100;


-- QUERY 4
SELECT * FROM BIGDRIVERS 
WHERE d_id IN (SELECT d_id from BIGCARS);

-- QUERY 5
SELECT * FROM BIGDRIVERS a where
EXISTS (SELECT * FROM BIGCARS B WHERE B.d_id = a.d_id);
